### ISSUE TITLE
Background music plays multiple times on round completion

### ISSUE THREAD

**Issue by CaptainDaVinci** [NITDgpOS/AirHockey#97]

**Comment by Aniq55** [comment]
Yes, I noticed this too

**Comment by thealphadollar** [comment]
I'm on this too :P

**Comment by vineetjc** [comment]
Hey, 
I've sent a pull request for this issue. It no longer plays multiple times after a round is completed.
Also, I realize it wasn't related to this issue, but I've added a line because of which now we can quit the game by clicking the close button, now the pygame screen will quit.

I hope it helps :)
